### ISSUE TITLE
Requests not going through to Rails

### ISSUE THREAD

**Issue by drnic** [drogus/bulk_api#12]
I don't know how to debug this, or if its happening to others, but the changes/commits AND initial data loading aren't generating requests to the Rails app.

https://github.com/drnic/todos-bulk-api-demo

I've also tried to recreate the app via http://sproutguides-drogus.strobeapp.com/rails.html and I'm not seeing any traffic to the server.

Does it work for other people, is there a regression (no idea how) or any ideas why I'm having this experience?

**Comment by aflatter** [comment]
This probably means that the data source is not successfully loaded. I ran into this a few days ago. If you're using `bulk_data_source` from master, the reason might be that Piotr changed naming to `BulkApi.BulkDataSource`.

**Comment by drnic** [comment]
Thanks for spotting that. I've fixed it and now I get real error/warnings in my console:

On page load - https://skitch.com/drnic/frgnx/todos-on-page-load

On createRecord - https://skitch.com/drnic/frgn1/todos

**Comment by drnic** [comment]
That was in the app built from the guide. In the app I have in the repo, it is now working.

**Comment by aflatter** [comment]
Can you close this? I'm losing track. ;)

**Comment by drnic** [comment]
Yes
