### ISSUE TITLE
How do I trigger commitRecord on Todos.store for SC.TemplateView's with valueBinding?

### ISSUE THREAD

**Issue by drnic** [drogus/bulk_api#13]
How do I trigger commitRecord on Todos.store for SC.TemplateView's with valueBinding?

``` javascript
Todos.MarkDoneView = SC.Checkbox.extend({
  valueBinding: '.parentView.content.isDone',
  title: function() {
    return this.getPath('parentView.content.title') + 
            ' [' + this.getPath('parentView.content').statusString() + ']';
  }.property('.parentView.content.title', '.parentView.content.status').cacheable()

});
```

**Comment by drogus** [comment]
I think this is more SproutCore than bulk api issue and unfortunately I don't know the answer. @wycats said that most of the time you should just go with commitRecordsAutomatically and that's what I was using till now. Could you ask that question on sproutcore google groups and/or IRC?
