### ISSUE TITLE
Rename datasource to BulkApi.BulkDataSource

### ISSUE THREAD

**Issue by drnic** [drogus/bulk_api#5]
I think the `SC.` prefix is reserved for SproutCore distributed classes. Perhaps change the name of the data source to `BulkApi.BulkDataSource`?

**Comment by drogus** [comment]
Good idea, I'm not sure why have I used `SC.` in the first place...

**Comment by paceline** [comment]
Oh, you already renamed it to `BulkApi.BulkDataSource`. You might want to update your README, which still claims its named `SC.BulkDataSource`. Took me a while to figure that one out...

Thanks

**Comment by drogus** [comment]
Sorry :)

Fixed.
