### ISSUE TITLE
Working example app repo

### ISSUE THREAD

**Issue by drnic** [drogus/bulk_api#7]
In the readme, perhaps link to https://github.com/drnic/todos-bulk-api-demo as a working example app?

**Comment by aflatter** [comment]
Argh, sorry. Should have checked the issues list first ;-) We're spamming Piotr quite a bit here.

https://github.com/drogus/bulk_api/pull/8

**Comment by drogus** [comment]
Actually I prepared small guide a while ago, but didn't have time to get rid of a few bugs in SC, the guide is here: http://sproutguides-drogus.strobeapp.com/rails.html, I'll try to check what's working and what needs to be done to get it all fixed. Possibly I could also write how to use it with SC 2.0 apps

**Comment by drnic** [comment]
Can you promote your own guide in the README? I had to search the closed tickets to find the URL again :)
